train_dir = 'train'
val_dir = 'validate'
test_dir = 'test'
batch_size = 8
logfile = 'train.log'
learn_rate = 0.01
lr_decay = 0.9
iterations = 5
steps_per_epoch = 2000
val_per_epoch = 100
epochs = 5
base_model = "simple_convolutional"
last = 0
in_dim = (299, 299, 3)
out_dim = 64
n_classes = 40
